#!/bin/bash

export PYTHONPATH=./odcs-common:./odcs-server:./odcs-client

ODCS_DEVELOPER_ENV=1 python odcs-server/odcs/server/manage.py upgradedb
ODCS_DEVELOPER_ENV=1 python odcs-server/odcs/server/manage.py db migrate
