version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.9-management
        environment:
            RABBITMQ_NODENAME: rabbitmq@localhost
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - 5672:5672
            - 15672:15672
            - 15692:15692
        volumes:
            - odcs-rabbitmq:/var/lib/rabbitmq/:z

    postgres:
        image: postgres:9
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - odcs-postgres:/var/lib/postgresql/data

    backend:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                cacert_url: https://password.corp.redhat.com/RH-IT-Root-CA.crt
        env_file:
            - .env
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
              celery-3 -b rabbitmq -A odcs.server.celery_tasks worker --loglevel=info -Q pungi_composes,pulp_composes,cleanup
        volumes:
            - ".:/src:z"
            - odcs-composes:/mnt/odcs:z
        depends_on:
            - rabbitmq
            - postgres

    frontend:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - .env
        entrypoint: ["/bin/sh","-c"]
        command:
            - |
              sleep 10
              python3 /src/server/odcs/server/manage.py db upgrade
              python3 /src/server/odcs/server/manage.py run --host 0.0.0.0
        depends_on:
            - rabbitmq
            - postgres
        ports:
            - 5000:5000
        volumes:
            - ".:/src:z"
            -  odcs-composes:/mnt/odcs:z

    static:
        image: httpd:2.4
        ports:
            - 8080:80
        volumes:
            - odcs-composes:/usr/local/apache2/htdocs/:z

    beat:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - .env
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
              celery-3 -b rabbitmq -A odcs.server.celery_tasks beat --loglevel=debug
        depends_on:
            - rabbitmq
        volumes:
            - ".:/src:z"
            - odcs-composes:/mnt/odcs:z

volumes:
    odcs-composes:
    odcs-rabbitmq:
    odcs-postgres:
