FROM quay.io/exd-guild-compose/odcs:latest
LABEL \
    name="ODCS test" \
    description="Run tests using tox" \
    vendor="ODCS developers" \
    license="GPLv2+"

RUN dnf -y update && dnf -y install \
        gcc \
        krb5-devel \
        python3-sphinx \
        python3-sphinxcontrib-httpdomain \
        python3-tox \
    && dnf clean all

WORKDIR /src

COPY . .

CMD ["tox"]
