#!/bin/bash

export PYTHONPATH=`pwd`/common:`pwd`/server:`pwd`/client
export ODCS_DEVELOPER_ENV=1

celery -A odcs.server.celery_tasks worker --loglevel=info -Q pungi_composes,pulp_composes &
PIDS[0]=$!

trap "kill ${PIDS[*]}" SIGINT

python server/odcs/server/manage.py runssl
if (($? != 0)); then
    wait
fi
