#!/bin/bash

export PYTHONPATH=./common:./server:./client
export ODCS_DEVELOPER_ENV=1

python server/odcs//server/manage.py runbackend &
PIDS[0]=$!

trap "kill ${PIDS[*]}" SIGINT

python server/odcs/server/manage.py runssl
if (($? != 0)); then
    wait
fi
