#!/bin/bash

if [ $# -gt 3 ]; then
    data="{\"source\": {\"type\": \"$1\", \"source\": \"$2\", \"packages\": [\"$3\"]}, \"seconds-to-live\": $4}"
elif [ $# -gt 2 ]; then
    data="{\"source\": {\"type\": \"$1\", \"source\": \"$2\", \"packages\": [\"$3\"]}}"
else
    data="{\"source\": {\"type\": \"$1\", \"source\": \"$2\"}}"
fi

curl --data "$data" localhost:5005/odcs/1/composes/

