"""Create user model

Revision ID: 758c0ce100a8
Revises: 566733ac3811
Create Date: 2017-07-06 11:39:46.952219

"""

# revision identifiers, used by Alembic.
revision = '758c0ce100a8'
down_revision = '566733ac3811'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
